name: game_ex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

