name: game_ex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  get_it: ^7.2.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

